#tasks file

#- debug: msg="{{ ansible_facts }}"
#- debug: msg="{{ ansible_facts.nodename }}"
#- debug: msg="{{ ansible_facts.hostname }}"  

- name: check version
  debug: msg="CentOS7"
  when:
    - ansible_facts.distribution_major_version == "7"

- name: check version
  debug: msg="CentOS8"
  when:
    - ansible_facts.distribution_major_version == "8"

########################################################
## 鍵の作成と配布
#- name: Create .ssh directory
#  file:
#    path: /root/.ssh
#    state: directory
#    owner: root
#    group: root
#    mode: '0700'
#
#- name: get id_rsa.pub from workstation
#  copy:
#    src: /home/vagrant/terraform-ibmcloud-vsi/id_rsa.pub
#    dest: /root/.ssh/authorized_keys
#    owner: root
#    group: root
#    mode: '0400'    
#
#####################################################
- name: Ensure group "origin" exists
  group:
    name:  origin
    state: present
- name: Add the user 'origin' with a bash shell,
  user:
    name:  origin
    shell: /bin/bash
    group: origin
- name: add sudoers
  template:
    src:  openshift.j2
    dest: /etc/sudoers.d/openshift
    owner: root
    group: root
    mode: 0440
- name: mkdir .ssh directory
  file:
    path: /home/origin/.ssh
    state: directory
    owner: origin
    group: origin
    mode: '0700'
- name: ssh config
  template:
    src:  ssh_config.j2
    dest: /home/origin/.ssh/config
    owner: origin
    group: origin
    mode: 0600
- name: get id_rsa.pub from workstation
  copy:
    src: /home/vagrant/terraform-ibmcloud-vsi/id_rsa.pub
    dest: /home/origin/.ssh/authorized_keys
    owner: origin
    group: origin
    mode: '0400'
- name: get id_rsa from workstation
  copy:
    src: /home/vagrant/terraform-ibmcloud-vsi/id_rsa
    dest: /home/origin/.ssh/id_rsa
    owner: origin
    group: origin
    mode: '0400'
#####################################################
## 必要なソフトのインストール
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - centos-release-openshift-origin311
      - epel-release
      #- docker
      - git
      - pyOpenSSL
      - NetworkManager
      - lvm2
      - flannel
#####################################################
#- name: Start docker
#  systemd:
#    name: docker.service
#    state: started
#    enabled: yes
#####################################################
- name: Start NetworkManger
  systemd:
    name: NetworkManager.service
    state: started
    enabled: yes
#####################################################
- name: copy hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
- name: Clone openshift-ansible
  shell: |
    if [ ! -d openshift-ansible ]; then
      git clone https://github.com/openshift/openshift-ansible -b release-3.11
    else 
      cd openshift-ansible
      git pull
    fi
    exit 0
  become: true
  become_user: origin
  args:
    chdir: /home/origin
- name: copy invetroy for openshift
  copy:
    src: /home/vagrant/terraform-ibmcloud-vsi/playbooks/hosts.openshift3
    dest: /home/origin/hosts.openshift3
    owner: origin
    group: origin
    mode: '0400'
- name: copy ansible.cfg
  copy:
    src: /home/vagrant/terraform-ibmcloud-vsi/ansible.cfg
    dest: /home/origin/ansible.cfg
    owner: origin
    group: origin
    mode: '0400'
#####################################################
# このタスクはDockerを導入する前に実行しなければならない
- name: docker storage setup
  template:
    src: docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode:  0644
    backup: yes
  
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-1.13.1

# こちらはDockerの機能なので導入後でないと実行できない    
- name: Globally disable the EPEL
  command: docker-storage-setup

# Dockerスタート
- name: Start docker
  systemd:
    name: docker.service
    state: started
    enabled: yes

  
