- hosts: nodes
  connection: ssh
  become: yes
  gather_facts: True

  tasks:
  - name: include vars
    include_vars: versions.yml

  ## Docker CE のインストール
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install packages
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'nfs-common']
      state: present
      update_cache: yes

  - name: Install Docker-CE
    apt:
      name: docker-ce{{ docker_version }}
      state: present
      update_cache: yes

  - name: usermod -aG docker vagrant
    user:
      name: vagrant
      groups: docker
      